# vars must be defined to be used
# format:
# key: ${ENV_VAR}
# key: ${ENV_VAR-:default}
# key: value
# and "%{key}" is used for settings values if available
# %% is used to escape this % special character in your config
variables:
  node_name_prefix: ${NODE_NAME_PREFIX:-node}
  node_hostname_prefix: ${NODE_HOSTNAME_PREFIX:-node}
  node_domain_affix: ${NODE_DOMAIN_AFFIX:-local}
  # some_env: ${MY_VAR:-value}-affix
  # env_key: value



# vagrant related settings
vagrant:
  # vagrant plugins are actually rubygems so you can declare to use any rubygems
  # common config level
  plugins: []
    # - _id: "0"
    #   name: vagrant-gatling-rsync
    #   version: "" # empty means latest by default
    #   state: installed # uninstalled
    #   enabled: true
    #   config_key: gatling
    #   options:
    #     latency: 0.5
    #     time_format: "%H:%M:%S"
    #     rsync_on_startup: true
    #
    # Plugin for vmware_desktop
    # - _id: "1"
    #   name: vagrant-vmware-desktop
    #   version: "" # empty means latest by default
    #   state: installed
    #   enabled: true


# default settings for all nodes
default:
  vm:
    box: bento/ubuntu-18.04
    box_version:
    box_url:
    synced_folders: []

  providers:
    - _id: "0"
      enabled: true
      type: virtualbox
      require_version: ">= 5.2"
      gui: false
      memory: 1024
      description: "%{node_name_prefix} #{Time.now.getutc.to_i}"

    # you need to install vagrant-vmware-desktop first before use this provider
    # see the installation steps at https://www.vagrantup.com/docs/vmware/installation.html
    # or better when you configure the plugins for automation instead of manual
    # - _id: "1"
    #   enabled: true
    #   type: vmware_desktop
    #   gui: false
    #   clone_directory: "./.vagrant" # Path for storing VMware clones. This value can also be set using the VAGRANT_VMWARE_CLONE_DIRECTORY environment variable. This defaults to ./.vagrant
    #   enable_vmrun_ip_lookup: true # This defaults to true
    #   vmx:
    #     memsize: 1024
    #     numvcpus: 2
    #
    #    More setting in https://www.vagrantup.com/docs/vmware/configuration.html

    # - _id: "2"
    #   enabled: true
    #   type: docker
    #   image: bento/ubuntu-18.04 # require
    #   build_dir: "." # require
    #   git_repo: # require
    # other settings in https://www.vagrantup.com/docs/docker/configuration.html

  provisioners: []

  # default node config level
  plugins: []

# specific nodes, each node will override the default
nodes:
  - _id: "0"
    name: "%{node_name_prefix}-01"
    primary: true
    vm:
      hostname: "%{node_hostname_prefix}-01.%{node_domain_affix}"
