# vars must be defined to be used
# format:
# key: ${ENV_VAR}
# key: ${ENV_VAR-:default}
# key: value
# and "%{key}" is used for settings values if available
# %% is used to escape this % special character in your config
variables:
  node_name_prefix: ${NODE_NAME_PREFIX:-k8s}
  node_hostname_prefix: ${NODE_HOSTNAME_PREFIX:-k8s}
  node_domain_affix: ${NODE_DOMAIN_AFFIX:-local}

vagrant:
  # vagrant plugins are actually rubygems so you can declare to use any rubygems
  # common config level
  plugins:
    - _id: "essential-1"
      name: vagrant-cachier
      version: ""
      state: "installed"
      enabled: true

# default settings for all nodes
default:
  vm:
    box: bento/ubuntu-18.04
    box_version:
    box_url:
    synced_folders: []

  providers:
    - _id: "1"
      enabled: true
      type: vmware-desktop
      gui: false
      memory: 2048

  provisioners: []

  # default node config level
  plugins: []

# specific nodes, each node will override the default
  nodes:
    - _id: "0" # This node is defined by default.
      vm:
        networks:
          - _id: "0"
            type: public_network
      plugins:
        - _id: "entry-0"
          name: vagrant-hostmanager
          config_key: hostmanager
          enabled: true
          options:
            aliases: # set domain aliases for the master node
              - "%{node_hostname_prefix}.%{node_domain_affix}"

    # Add more node, if you need
    - _id: "1"
      name: "%{node_name_prefix}-02"
      vm:
        hostname: "%{node_hostname_prefix}-02.%{node_domain_affix}"
        networks:
          - _id: "0"
            type: public_network
            ip: 192.168.1.111